export type Difficulty = 'Easy' | 'Medium' | 'Hard' | 'Expert';

export interface SlangInfo {
  term: string;
  meaning: string;
  era: string;
  eraOptions: string[];
  meaningOptions: string[];
}

export interface PhraseInfo {
  phrase: string;
  origin: string;
  meaning: string;
  originOptions: string[];
  meaningOptions: string[];
}

export interface WordEntry {
  id: string;
  word: string;
  difficulty: Difficulty;
  category: string;
  meanings: string[];
  mcqDecoys: string[];
  slangInfo?: SlangInfo;
  phraseInfo?: PhraseInfo;
}

export const WORD_POOL: WordEntry[] = [
  // ─── EASY (30) ───────────────────────────────────────────────────────────────
  {
    id: 'sage',
    word: 'Sage',
    difficulty: 'Easy',
    category: 'Nature & Wisdom',
    meanings: [
      'A herb used in cooking',
      'A wise and experienced person',
      'A grey-green colour',
    ],
    mcqDecoys: ['A type of fish', 'A musical instrument', 'A sharp tool'],
    slangInfo: {
      term: 'sage',
      meaning: 'Wise beyond years',
      era: '1990s',
      eraOptions: ['1970s', '1980s', '1990s', '2000s'],
      meaningOptions: ['Foolish', 'Wise beyond years', 'Very old', 'Cautious'],
    },
  },
  {
    id: 'fair',
    word: 'Fair',
    difficulty: 'Easy',
    category: 'Justice & Events',
    meanings: [
      'An outdoor event with rides and games',
      'Just and unbiased',
      'Light in complexion or colour',
    ],
    mcqDecoys: ['A dark tunnel', 'A legal contract', 'A heavy rain'],
    phraseInfo: {
      phrase: 'Fair and square',
      origin: 'Middle English',
      meaning: 'Done honestly and correctly',
      originOptions: ['Latin', 'Middle English', 'Old Norse', 'French'],
      meaningOptions: [
        'Done dishonestly',
        'Done honestly and correctly',
        'Done quickly',
        'Done with help',
      ],
    },
  },
  {
    id: 'seal',
    word: 'Seal',
    difficulty: 'Easy',
    category: 'Animals & Closures',
    meanings: [
      'A marine mammal with flippers',
      'To close something tightly',
      'An official stamp or emblem',
    ],
    mcqDecoys: ['A type of bird', 'A kitchen utensil', 'A school subject'],
  },
  {
    id: 'duck',
    word: 'Duck',
    difficulty: 'Easy',
    category: 'Birds & Movement',
    meanings: [
      'A water bird',
      'To lower your head quickly to avoid something',
      'A score of zero in cricket',
    ],
    mcqDecoys: ['A tall building', 'A type of pasta', 'A warm blanket'],
    slangInfo: {
      term: 'duck',
      meaning: 'To avoid a question or responsibility',
      era: '1800s',
      eraOptions: ['1600s', '1700s', '1800s', '1900s'],
      meaningOptions: [
        'To answer directly',
        'To avoid a question or responsibility',
        'To swim quickly',
        'To fall asleep',
      ],
    },
  },
  {
    id: 'bank',
    word: 'Bank',
    difficulty: 'Easy',
    category: 'Finance & Geography',
    meanings: [
      'A financial institution',
      'The side of a river',
      'To tilt an aircraft while turning',
    ],
    mcqDecoys: ['A type of fruit', 'A musical note', 'A cooking method'],
    phraseInfo: {
      phrase: 'Break the bank',
      origin: 'Gambling terminology',
      meaning: 'To cost a very large amount of money',
      originOptions: ['Medical terminology', 'Gambling terminology', 'Military slang', 'Legal jargon'],
      meaningOptions: [
        'To save a lot of money',
        'To cost a very large amount of money',
        'To rob a bank',
        'To open a new account',
      ],
    },
  },
  {
    id: 'spring',
    word: 'Spring',
    difficulty: 'Easy',
    category: 'Seasons & Movement',
    meanings: [
      'The season after winter',
      'A coiled metal device that stores energy',
      'To jump or leap suddenly',
    ],
    mcqDecoys: ['A type of cheese', 'A legal document', 'A cloud formation'],
  },
  {
    id: 'rose',
    word: 'Rose',
    difficulty: 'Easy',
    category: 'Flowers & Colours',
    meanings: [
      'A flowering plant with thorns',
      'A pinkish colour',
      'Past tense of rise',
    ],
    mcqDecoys: ['A musical scale', 'A type of bread', 'A mathematical symbol'],
    phraseInfo: {
      phrase: 'Bed of roses',
      origin: 'Literary English',
      meaning: 'A comfortable or easy situation',
      originOptions: ['Old French', 'Literary English', 'Latin', 'Germanic'],
      meaningOptions: [
        'A difficult situation',
        'A comfortable or easy situation',
        'A garden feature',
        'A type of mattress',
      ],
    },
  },
  {
    id: 'light',
    word: 'Light',
    difficulty: 'Easy',
    category: 'Physics & Weight',
    meanings: [
      'Electromagnetic radiation visible to the eye',
      'Not heavy',
      'To ignite or set on fire',
    ],
    mcqDecoys: ['A type of metal', 'A legal term', 'A weather system'],
    slangInfo: {
      term: 'light',
      meaning: 'Easy or not serious',
      era: '1950s',
      eraOptions: ['1930s', '1940s', '1950s', '1960s'],
      meaningOptions: ['Very heavy', 'Easy or not serious', 'Bright and flashy', 'Old-fashioned'],
    },
  },
  {
    id: 'pool',
    word: 'Pool',
    difficulty: 'Easy',
    category: 'Water & Games',
    meanings: [
      'A body of still water',
      'A game played on a billiard table',
      'To combine resources together',
    ],
    mcqDecoys: ['A type of fabric', 'A cooking vessel', 'A legal agreement'],
  },
  {
    id: 'match',
    word: 'Match',
    difficulty: 'Easy',
    category: 'Sports & Fire',
    meanings: [
      'A small stick used to start a fire',
      'A sporting contest',
      'To correspond or be similar to',
    ],
    mcqDecoys: ['A type of plant', 'A banking term', 'A musical key'],
    phraseInfo: {
      phrase: 'Meet your match',
      origin: 'Old English',
      meaning: 'To encounter someone equally skilled',
      originOptions: ['Old English', 'French', 'Latin', 'Norse'],
      meaningOptions: [
        'To lose a competition',
        'To encounter someone equally skilled',
        'To find a partner',
        'To start a fire',
      ],
    },
  },
  {
    id: 'fire',
    word: 'Fire',
    difficulty: 'Easy',
    category: 'Elements & Employment',
    meanings: [
      'The process of combustion producing heat and light',
      'To dismiss someone from a job',
      'To shoot a weapon',
    ],
    mcqDecoys: ['A type of plant', 'A financial term', 'A cloud formation'],
    slangInfo: {
      term: 'fire',
      meaning: 'Excellent or impressive',
      era: '2010s',
      eraOptions: ['1990s', '2000s', '2010s', '2020s'],
      meaningOptions: ['Terrible', 'Excellent or impressive', 'On fire literally', 'Very angry'],
    },
  },
  {
    id: 'date',
    word: 'Date',
    difficulty: 'Easy',
    category: 'Time & Romance',
    meanings: [
      'A specific day in time',
      'A romantic outing',
      'A sweet fruit from a palm tree',
    ],
    mcqDecoys: ['A type of metal', 'A weather event', 'A musical term'],
  },
  {
    id: 'fly',
    word: 'Fly',
    difficulty: 'Easy',
    category: 'Insects & Aviation',
    meanings: [
      'A small winged insect',
      'To travel through the air',
      'The zip on a pair of trousers',
    ],
    mcqDecoys: ['A type of fish', 'A legal document', 'A kitchen tool'],
    slangInfo: {
      term: 'fly',
      meaning: 'Stylish and attractive',
      era: '1990s',
      eraOptions: ['1970s', '1980s', '1990s', '2000s'],
      meaningOptions: ['Boring and plain', 'Stylish and attractive', 'Very fast', 'Secretive'],
    },
  },
  {
    id: 'rock',
    word: 'Rock',
    difficulty: 'Easy',
    category: 'Geology & Music',
    meanings: [
      'A hard mineral substance',
      'A genre of music',
      'To move back and forth gently',
    ],
    mcqDecoys: ['A type of fabric', 'A cooking method', 'A legal procedure'],
    phraseInfo: {
      phrase: 'Rock the boat',
      origin: 'American English',
      meaning: 'To disturb an existing situation',
      originOptions: ['British English', 'American English', 'Australian English', 'Irish English'],
      meaningOptions: [
        'To sail a boat',
        'To disturb an existing situation',
        'To steady a boat',
        'To enjoy music',
      ],
    },
  },
  {
    id: 'jam',
    word: 'Jam',
    difficulty: 'Easy',
    category: 'Food & Music',
    meanings: [
      'A sweet fruit preserve',
      'To improvise music informally',
      'A traffic blockage',
    ],
    mcqDecoys: ['A legal term', 'A type of tool', 'A weather event'],
    slangInfo: {
      term: 'jam',
      meaning: 'A difficult situation or predicament',
      era: '1800s',
      eraOptions: ['1700s', '1800s', '1900s', '2000s'],
      meaningOptions: [
        'A musical session',
        'A difficult situation or predicament',
        'A sweet food',
        'A traffic event',
      ],
    },
  },
  {
    id: 'wave',
    word: 'Wave',
    difficulty: 'Easy',
    category: 'Ocean & Gestures',
    meanings: [
      'A ridge of water moving across the sea',
      'To move your hand as a greeting',
      'A sudden increase or surge',
    ],
    mcqDecoys: ['A type of stone', 'A cooking appliance', 'A legal notice'],
  },
  {
    id: 'key',
    word: 'Key',
    difficulty: 'Easy',
    category: 'Tools & Music',
    meanings: [
      'A metal device for opening locks',
      'A scale in music',
      'Most important or essential',
    ],
    mcqDecoys: ['A type of fruit', 'A weather term', 'A building material'],
    phraseInfo: {
      phrase: 'Key to success',
      origin: 'Modern English',
      meaning: 'The most important factor for achieving success',
      originOptions: ['Latin', 'French', 'Modern English', 'Old Norse'],
      meaningOptions: [
        'A physical key',
        'The most important factor for achieving success',
        'A musical key',
        'An old proverb',
      ],
    },
  },
  {
    id: 'box',
    word: 'Box',
    difficulty: 'Easy',
    category: 'Containers & Sports',
    meanings: [
      'A rectangular container',
      'To fight with fists as a sport',
      'A small compartment in a theatre',
    ],
    mcqDecoys: ['A type of plant', 'A weather condition', 'A financial term'],
  },
  {
    id: 'tip',
    word: 'Tip',
    difficulty: 'Easy',
    category: 'Money & Advice',
    meanings: [
      'A small extra payment for good service',
      'The pointed end of something',
      'A piece of useful advice',
    ],
    mcqDecoys: ['A type of fabric', 'A cooking method', 'A weather condition'],
    slangInfo: {
      term: 'tip',
      meaning: 'Inside information about something profitable',
      era: '1800s',
      eraOptions: ['1700s', '1800s', '1900s', '2000s'],
      meaningOptions: [
        'A gratuity payment',
        'Inside information about something profitable',
        'The end of an object',
        'A rubbish dump',
      ],
    },
  },
  {
    id: 'club',
    word: 'Club',
    difficulty: 'Easy',
    category: 'Groups & Sports',
    meanings: [
      'An organisation for people with shared interests',
      'A heavy stick used as a weapon',
      'A suit in playing cards',
    ],
    mcqDecoys: ['A type of insect', 'A musical note', 'A cooking ingredient'],
    phraseInfo: {
      phrase: 'Welcome to the club',
      origin: 'American slang',
      meaning: 'You share a common experience with others',
      originOptions: ['British slang', 'American slang', 'Australian slang', 'Irish slang'],
      meaningOptions: [
        'A formal welcome to a group',
        'You share a common experience with others',
        'An exclusive membership invitation',
        'A sarcastic dismissal',
      ],
    },
  },
  {
    id: 'net',
    word: 'Net',
    difficulty: 'Easy',
    category: 'Sports & Finance',
    meanings: [
      'An openwork fabric used in sports',
      'Remaining after deductions',
      'To catch something in a net',
    ],
    mcqDecoys: ['A type of stone', 'A weather phenomenon', 'A musical term'],
  },
  {
    id: 'cold',
    word: 'Cold',
    difficulty: 'Easy',
    category: 'Temperature & Illness',
    meanings: [
      'Having a low temperature',
      'A common illness causing a runny nose',
      'Unfriendly or emotionally distant',
    ],
    mcqDecoys: ['A type of metal', 'A legal document', 'A musical instrument'],
    slangInfo: {
      term: 'cold',
      meaning: 'Without preparation or warning',
      era: '1900s',
      eraOptions: ['1800s', '1900s', '1950s', '1980s'],
      meaningOptions: [
        'At low temperature',
        'Without preparation or warning',
        'Very successful',
        'Emotionally warm',
      ],
    },
  },
  {
    id: 'bill',
    word: 'Bill',
    difficulty: 'Easy',
    category: 'Money & Politics',
    meanings: [
      'A written statement of money owed',
      'A proposed law',
      'The beak of a bird',
    ],
    mcqDecoys: ['A type of plant', 'A cooking utensil', 'A weather system'],
  },
  {
    id: 'log',
    word: 'Log',
    difficulty: 'Easy',
    category: 'Nature & Records',
    meanings: [
      'A section of a tree trunk',
      'An official record of events',
      'To record data systematically',
    ],
    mcqDecoys: ['A type of insect', 'A musical scale', 'A financial instrument'],
    phraseInfo: {
      phrase: 'Log cabin',
      origin: 'American frontier',
      meaning: 'A small house built from logs',
      originOptions: ['British colonialism', 'American frontier', 'Scandinavian tradition', 'Canadian history'],
      meaningOptions: [
        'A luxury home',
        'A small house built from logs',
        'A type of holiday',
        'A treehouse',
      ],
    },
  },
  {
    id: 'pen',
    word: 'Pen',
    difficulty: 'Easy',
    category: 'Writing & Enclosures',
    meanings: [
      'A writing instrument using ink',
      'An enclosed area for animals',
      'A female swan',
    ],
    mcqDecoys: ['A type of fabric', 'A cooking method', 'A weather event'],
    slangInfo: {
      term: 'pen',
      meaning: 'Prison or penitentiary',
      era: '1900s',
      eraOptions: ['1800s', '1900s', '1950s', '1980s'],
      meaningOptions: [
        'A writing tool',
        'Prison or penitentiary',
        'An animal enclosure',
        'A type of sword',
      ],
    },
  },
  {
    id: 'bug',
    word: 'Bug',
    difficulty: 'Easy',
    category: 'Technology & Insects',
    meanings: [
      'A small insect',
      'An error in computer software',
      'To secretly listen to conversations',
    ],
    mcqDecoys: ['A type of plant', 'A weather term', 'A financial concept'],
  },
  {
    id: 'frame',
    word: 'Frame',
    difficulty: 'Easy',
    category: 'Structure & Photography',
    meanings: [
      'A border or structure surrounding something',
      'A single image in a film or video',
      'To falsely incriminate someone',
    ],
    mcqDecoys: ['A type of fabric', 'A cooking term', 'A musical key'],
    phraseInfo: {
      phrase: 'Frame of mind',
      origin: 'Old English',
      meaning: 'A particular mental or emotional state',
      originOptions: ['Latin', 'Old English', 'French', 'German'],
      meaningOptions: [
        'A picture frame',
        'A particular mental or emotional state',
        'A way of thinking about time',
        'A physical posture',
      ],
    },
  },
  {
    id: 'watch',
    word: 'Watch',
    difficulty: 'Easy',
    category: 'Time & Observation',
    meanings: [
      'A small timepiece worn on the wrist',
      'To look at or observe something',
      'A period of duty keeping guard',
    ],
    mcqDecoys: ['A type of jewel', 'A musical term', 'A cooking method'],
  },
  {
    id: 'mark',
    word: 'Mark',
    difficulty: 'Easy',
    category: 'Signs & Assessment',
    meanings: [
      'A visible impression or stain',
      'A grade given for school work',
      'To pay attention to something',
    ],
    mcqDecoys: ['A type of plant', 'A weather condition', 'A financial product'],
    slangInfo: {
      term: 'mark',
      meaning: 'A target or victim of a scam',
      era: '1800s',
      eraOptions: ['1700s', '1800s', '1900s', '2000s'],
      meaningOptions: [
        'A good student',
        'A target or victim of a scam',
        'A type of signature',
        'A German currency',
      ],
    },
  },
  {
    id: 'bat',
    word: 'Bat',
    difficulty: 'Easy',
    category: 'Animals & Sports',
    meanings: [
      'A nocturnal flying mammal',
      'A wooden or metal implement used in sports',
      'To hit something with a bat',
    ],
    mcqDecoys: ['A type of bird', 'A cooking utensil', 'A legal document'],
    phraseInfo: {
      phrase: 'Like a bat out of hell',
      origin: 'American slang',
      meaning: 'Moving extremely fast',
      originOptions: ['British English', 'American slang', 'Australian English', 'Irish English'],
      meaningOptions: [
        'Flying at night',
        'Moving extremely fast',
        'Acting strangely',
        'Moving very slowly',
      ],
    },
  },

  // ─── MEDIUM (28) ─────────────────────────────────────────────────────────────
  {
    id: 'pitch',
    word: 'Pitch',
    difficulty: 'Medium',
    category: 'Sports & Sound',
    meanings: [
      'A playing field for sports',
      'The highness or lowness of a musical sound',
      'A persuasive sales talk',
      'A dark sticky substance from coal',
    ],
    mcqDecoys: ['A type of fabric', 'A cooking method', 'A mathematical function'],
    phraseInfo: {
      phrase: 'Pitch perfect',
      origin: 'Musical terminology',
      meaning: 'Absolutely accurate in musical tone',
      originOptions: ['Sports terminology', 'Musical terminology', 'Sales terminology', 'Military terminology'],
      meaningOptions: [
        'A perfect sports field',
        'Absolutely accurate in musical tone',
        'A flawless sales pitch',
        'Completely dark',
      ],
    },
  },
  {
    id: 'bark',
    word: 'Bark',
    difficulty: 'Medium',
    category: 'Nature & Animals',
    meanings: [
      'The outer covering of a tree',
      'The sharp sound a dog makes',
      'To speak in a sharp commanding tone',
    ],
    mcqDecoys: ['A type of stone', 'A cooking utensil', 'A financial term'],
    slangInfo: {
      term: 'bark',
      meaning: 'To shout angrily at someone',
      era: '1700s',
      eraOptions: ['1600s', '1700s', '1800s', '1900s'],
      meaningOptions: [
        'To speak softly',
        'To shout angrily at someone',
        'To laugh loudly',
        'To complain quietly',
      ],
    },
  },
  {
    id: 'crane',
    word: 'Crane',
    difficulty: 'Medium',
    category: 'Birds & Machinery',
    meanings: [
      'A large wading bird with long legs',
      'A machine for lifting heavy objects',
      'To stretch your neck to see something',
    ],
    mcqDecoys: ['A type of insect', 'A cooking appliance', 'A legal term'],
  },
  {
    id: 'bear',
    word: 'Bear',
    difficulty: 'Medium',
    category: 'Animals & Finance',
    meanings: [
      'A large omnivorous mammal',
      'An investor who expects prices to fall',
      'To carry or endure something',
    ],
    mcqDecoys: ['A type of plant', 'A musical note', 'A weather phenomenon'],
    phraseInfo: {
      phrase: 'Bear the brunt',
      origin: 'Old English',
      meaning: 'To suffer the main force of something',
      originOptions: ['French', 'Old English', 'Latin', 'German'],
      meaningOptions: [
        'To carry a bear',
        'To suffer the main force of something',
        'To endure cold weather',
        'To invest in stocks',
      ],
    },
  },
  {
    id: 'cast',
    word: 'Cast',
    difficulty: 'Medium',
    category: 'Performance & Fishing',
    meanings: [
      'The actors in a film or play',
      'To throw a fishing line into water',
      'A plaster mould for a broken bone',
    ],
    mcqDecoys: ['A type of fabric', 'A cooking ingredient', 'A weather system'],
    slangInfo: {
      term: 'cast',
      meaning: 'To broadcast something widely',
      era: '1920s',
      eraOptions: ['1900s', '1920s', '1950s', '1980s'],
      meaningOptions: [
        'To throw something',
        'To broadcast something widely',
        'To act in a film',
        'To set a bone',
      ],
    },
  },
  {
    id: 'novel',
    word: 'Novel',
    difficulty: 'Medium',
    category: 'Literature & Innovation',
    meanings: [
      'A long fictional book',
      'New and original',
      'An innovative idea never seen before',
    ],
    mcqDecoys: ['A type of music', 'A cooking method', 'A weather term'],
  },
  {
    id: 'pupil',
    word: 'Pupil',
    difficulty: 'Medium',
    category: 'Education & Anatomy',
    meanings: [
      'A student at school',
      'The dark circular opening in the eye',
      'A person who learns from a master',
    ],
    mcqDecoys: ['A type of plant', 'A financial term', 'A weather condition'],
    phraseInfo: {
      phrase: 'Pupil of the eye',
      origin: 'Latin pupilla',
      meaning: 'The aperture in the iris that controls light entry',
      originOptions: ['Greek', 'Latin pupilla', 'French', 'Old English'],
      meaningOptions: [
        'A student studying vision',
        'The aperture in the iris that controls light entry',
        'The whites of the eye',
        'The outer part of the eye',
      ],
    },
  },
  {
    id: 'strike',
    word: 'Strike',
    difficulty: 'Medium',
    category: 'Labour & Sports',
    meanings: [
      'A work stoppage by employees',
      'To hit something forcefully',
      'Knocking down all pins in bowling',
    ],
    mcqDecoys: ['A type of fabric', 'A cooking method', 'A financial product'],
    slangInfo: {
      term: 'strike',
      meaning: 'To make a strong impression',
      era: '1800s',
      eraOptions: ['1700s', '1800s', '1900s', '2000s'],
      meaningOptions: [
        'To hit physically',
        'To make a strong impression',
        'To stop working',
        'To score in bowling',
      ],
    },
  },
  {
    id: 'lead',
    word: 'Lead',
    difficulty: 'Medium',
    category: 'Metals & Direction',
    meanings: [
      'A heavy grey metal',
      'To guide or be in front of a group',
      'The main role in a performance',
    ],
    mcqDecoys: ['A type of plant', 'A cooking term', 'A weather phenomenon'],
  },
  {
    id: 'palm',
    word: 'Palm',
    difficulty: 'Medium',
    category: 'Anatomy & Plants',
    meanings: [
      'The inner surface of the hand',
      'A tropical tree',
      'To conceal something in the hand',
    ],
    mcqDecoys: ['A type of metal', 'A cooking utensil', 'A legal document'],
    phraseInfo: {
      phrase: 'Palm off',
      origin: 'Old English',
      meaning: 'To pass something inferior to someone deceptively',
      originOptions: ['French', 'Old English', 'Latin', 'Norse'],
      meaningOptions: [
        'To wave goodbye',
        'To pass something inferior to someone deceptively',
        'To read someone\'s palm',
        'To harvest palm trees',
      ],
    },
  },
  {
    id: 'score',
    word: 'Score',
    difficulty: 'Medium',
    category: 'Numbers & Music',
    meanings: [
      'Points achieved in a game',
      'Written notation for music',
      'Twenty of something',
      'To obtain or achieve something',
    ],
    mcqDecoys: ['A type of plant', 'A weather term', 'A cooking method'],
    slangInfo: {
      term: 'score',
      meaning: 'To obtain drugs illegally',
      era: '1950s',
      eraOptions: ['1930s', '1940s', '1950s', '1960s'],
      meaningOptions: [
        'To win a game',
        'To obtain drugs illegally',
        'To write music',
        'To count to twenty',
      ],
    },
  },
  {
    id: 'drive',
    word: 'Drive',
    difficulty: 'Medium',
    category: 'Transport & Motivation',
    meanings: [
      'To operate a vehicle',
      'Strong motivation or ambition',
      'A road leading to a house',
    ],
    mcqDecoys: ['A type of insect', 'A legal term', 'A cooking ingredient'],
  },
  {
    id: 'staff',
    word: 'Staff',
    difficulty: 'Medium',
    category: 'People & Music',
    meanings: [
      'The employees of an organisation',
      'A long stick used as a walking aid or weapon',
      'The five lines on which music is written',
    ],
    mcqDecoys: ['A type of plant', 'A cooking method', 'A weather system'],
    phraseInfo: {
      phrase: 'Staff of life',
      origin: 'Biblical English',
      meaning: 'Bread, considered essential food',
      originOptions: ['Greek mythology', 'Biblical English', 'Roman history', 'Norse mythology'],
      meaningOptions: [
        'Employees of a hospital',
        'Bread, considered essential food',
        'A walking stick',
        'The five music lines',
      ],
    },
  },
  {
    id: 'suit',
    word: 'Suit',
    difficulty: 'Medium',
    category: 'Clothing & Law',
    meanings: [
      'A matching jacket and trousers',
      'A legal case or lawsuit',
      'A category of playing cards',
    ],
    mcqDecoys: ['A type of plant', 'A cooking method', 'A weather phenomenon'],
    slangInfo: {
      term: 'suit',
      meaning: 'A corporate executive or person in authority',
      era: '1970s',
      eraOptions: ['1950s', '1960s', '1970s', '1980s'],
      meaningOptions: [
        'A set of clothing',
        'A corporate executive or person in authority',
        'A card game',
        'A legal representative',
      ],
    },
  },
  {
    id: 'buff',
    word: 'Buff',
    difficulty: 'Medium',
    category: 'Colours & Enthusiasm',
    meanings: [
      'A pale yellow-beige colour',
      'An enthusiastic fan or expert',
      'To polish or shine a surface',
    ],
    mcqDecoys: ['A type of metal', 'A legal process', 'A weather condition'],
  },
  {
    id: 'track',
    word: 'Track',
    difficulty: 'Medium',
    category: 'Music & Transport',
    meanings: [
      'A path or course for racing',
      'A song on an album',
      'To follow or monitor something',
    ],
    mcqDecoys: ['A type of plant', 'A cooking technique', 'A financial term'],
    phraseInfo: {
      phrase: 'On track',
      origin: 'Railway terminology',
      meaning: 'Progressing as expected towards a goal',
      originOptions: ['Military terminology', 'Railway terminology', 'Athletic terminology', 'Music terminology'],
      meaningOptions: [
        'Literally on a railway',
        'Progressing as expected towards a goal',
        'Following an animal\'s tracks',
        'Playing a music track',
      ],
    },
  },
  {
    id: 'base',
    word: 'Base',
    difficulty: 'Medium',
    category: 'Military & Chemistry',
    meanings: [
      'The bottom or foundation of something',
      'A military installation',
      'The opposite of an acid in chemistry',
    ],
    mcqDecoys: ['A type of fruit', 'A weather term', 'A cooking ingredient'],
    slangInfo: {
      term: 'base',
      meaning: 'Morally low or despicable',
      era: '1500s',
      eraOptions: ['1400s', '1500s', '1600s', '1700s'],
      meaningOptions: [
        'At the bottom',
        'Morally low or despicable',
        'A military camp',
        'An alkaline substance',
      ],
    },
  },
  {
    id: 'press',
    word: 'Press',
    difficulty: 'Medium',
    category: 'Media & Physical Force',
    meanings: [
      'Newspapers and journalists collectively',
      'To push firmly on something',
      'To iron clothes',
    ],
    mcqDecoys: ['A type of insect', 'A cooking vessel', 'A weather event'],
  },
  {
    id: 'pound',
    word: 'Pound',
    difficulty: 'Medium',
    category: 'Currency & Force',
    meanings: [
      'The British unit of currency',
      'To hit something repeatedly and hard',
      'A unit of weight equal to 16 ounces',
    ],
    mcqDecoys: ['A type of plant', 'A musical term', 'A weather phenomenon'],
    phraseInfo: {
      phrase: 'Pound of flesh',
      origin: 'Shakespeare\'s Merchant of Venice',
      meaning: 'Something owed that is cruel to collect',
      originOptions: ['Biblical origins', 'Shakespeare\'s Merchant of Venice', 'Greek mythology', 'Roman law'],
      meaningOptions: [
        'A weight measurement',
        'Something owed that is cruel to collect',
        'A piece of meat',
        'British currency payment',
      ],
    },
  },
  {
    id: 'bridge',
    word: 'Bridge',
    difficulty: 'Medium',
    category: 'Architecture & Music',
    meanings: [
      'A structure spanning a gap or river',
      'A card game for four players',
      'The middle section of a song',
    ],
    mcqDecoys: ['A type of insect', 'A cooking method', 'A weather system'],
    slangInfo: {
      term: 'bridge',
      meaning: 'To connect two different things or ideas',
      era: '1900s',
      eraOptions: ['1800s', '1900s', '1950s', '2000s'],
      meaningOptions: [
        'To build a bridge',
        'To connect two different things or ideas',
        'To play cards',
        'To compose music',
      ],
    },
  },
  {
    id: 'mole',
    word: 'Mole',
    difficulty: 'Medium',
    category: 'Animals & Chemistry',
    meanings: [
      'A small burrowing mammal',
      'A unit of measurement in chemistry',
      'A spy embedded within an organisation',
    ],
    mcqDecoys: ['A type of bird', 'A cooking utensil', 'A weather phenomenon'],
  },
  {
    id: 'plot',
    word: 'Plot',
    difficulty: 'Medium',
    category: 'Stories & Schemes',
    meanings: [
      'The main events of a story',
      'A secret plan or scheme',
      'A small piece of land',
    ],
    mcqDecoys: ['A type of fabric', 'A cooking method', 'A financial term'],
    phraseInfo: {
      phrase: 'Lose the plot',
      origin: 'British English',
      meaning: 'To become confused or lose control',
      originOptions: ['American English', 'British English', 'Australian English', 'Irish English'],
      meaningOptions: [
        'To forget a story',
        'To become confused or lose control',
        'To sell land',
        'To cancel a scheme',
      ],
    },
  },
  {
    id: 'spell',
    word: 'Spell',
    difficulty: 'Medium',
    category: 'Magic & Language',
    meanings: [
      'A magical incantation',
      'To write or say the letters of a word',
      'A short period of time or activity',
    ],
    mcqDecoys: ['A type of plant', 'A musical term', 'A weather tool'],
    slangInfo: {
      term: 'spell',
      meaning: 'A period of illness or bad luck',
      era: '1800s',
      eraOptions: ['1700s', '1800s', '1900s', '2000s'],
      meaningOptions: [
        'A magical charm',
        'A period of illness or bad luck',
        'The act of spelling words',
        'A rest period',
      ],
    },
  },
  {
    id: 'sound',
    word: 'Sound',
    difficulty: 'Medium',
    category: 'Physics & Health',
    meanings: [
      'Vibrations that travel through air and are heard',
      'In good condition or health',
      'A long narrow body of water',
    ],
    mcqDecoys: ['A type of metal', 'A cooking technique', 'A legal term'],
  },
  {
    id: 'course',
    word: 'Course',
    difficulty: 'Medium',
    category: 'Education & Direction',
    meanings: [
      'A series of lessons on a subject',
      'The route taken by a ship or aircraft',
      'A part of a meal served at one time',
    ],
    mcqDecoys: ['A type of plant', 'A weather phenomenon', 'A financial product'],
    phraseInfo: {
      phrase: 'Of course',
      origin: 'Old French cours',
      meaning: 'Certainly or naturally',
      originOptions: ['Latin', 'Old French cours', 'Middle English', 'Norse'],
      meaningOptions: [
        'Referring to a course of study',
        'Certainly or naturally',
        'Along a certain route',
        'A part of a meal',
      ],
    },
  },
  {
    id: 'point',
    word: 'Point',
    difficulty: 'Medium',
    category: 'Geometry & Purpose',
    meanings: [
      'A sharp tip or end',
      'The purpose or meaning of something',
      'A unit of scoring in a game',
    ],
    mcqDecoys: ['A type of plant', 'A cooking method', 'A weather condition'],
    slangInfo: {
      term: 'point',
      meaning: 'The essential argument or message',
      era: '1300s',
      eraOptions: ['1200s', '1300s', '1400s', '1500s'],
      meaningOptions: [
        'A sharp object',
        'The essential argument or message',
        'A score in a game',
        'A geographical location',
      ],
    },
  },
  {
    id: 'board',
    word: 'Board',
    difficulty: 'Medium',
    category: 'Governance & Materials',
    meanings: [
      'A flat piece of wood or other material',
      'A group of people who manage an organisation',
      'To get onto a vehicle',
    ],
    mcqDecoys: ['A type of insect', 'A musical key', 'A weather event'],
  },
  {
    id: 'train',
    word: 'Train',
    difficulty: 'Medium',
    category: 'Transport & Development',
    meanings: [
      'A series of carriages pulled by a locomotive',
      'To practise or develop a skill',
      'The flowing part of a wedding dress',
    ],
    mcqDecoys: ['A type of fruit', 'A cooking method', 'A financial term'],
    phraseInfo: {
      phrase: 'Train of thought',
      origin: 'Latin sequentia',
      meaning: 'A connected series of thoughts or ideas',
      originOptions: ['Old English', 'Latin sequentia', 'French', 'German'],
      meaningOptions: [
        'Thoughts about trains',
        'A connected series of thoughts or ideas',
        'A type of memory technique',
        'The noise a train makes',
      ],
    },
  },

  // ─── HARD (25) ───────────────────────────────────────────────────────────────
  {
    id: 'bolt',
    word: 'Bolt',
    difficulty: 'Hard',
    category: 'Fasteners & Weather',
    meanings: [
      'A metal fastener used with a nut',
      'A flash of lightning',
      'To run away suddenly',
      'To lock a door with a sliding bar',
    ],
    mcqDecoys: ['A type of plant', 'A cooking method', 'A musical term'],
    phraseInfo: {
      phrase: 'Bolt from the blue',
      origin: 'Classical Latin',
      meaning: 'A sudden and unexpected event',
      originOptions: ['Old Norse', 'Classical Latin', 'Middle English', 'French'],
      meaningOptions: [
        'A lightning strike',
        'A sudden and unexpected event',
        'Something coming from the sky',
        'A fast runner',
      ],
    },
  },
  {
    id: 'tender',
    word: 'Tender',
    difficulty: 'Hard',
    category: 'Commerce & Emotion',
    meanings: [
      'Gentle and caring in feeling',
      'A formal bid for a contract',
      'A vehicle carrying fuel for a steam engine',
      'Soft and easy to chew (food)',
    ],
    mcqDecoys: ['A type of insect', 'A weather tool', 'A musical note'],
    slangInfo: {
      term: 'tender',
      meaning: 'Legal tender: money accepted as payment',
      era: '1500s',
      eraOptions: ['1400s', '1500s', '1600s', '1700s'],
      meaningOptions: [
        'Something soft to touch',
        'Legal tender: money accepted as payment',
        'A formal bid',
        'A type of chicken',
      ],
    },
  },
  {
    id: 'vault',
    word: 'Vault',
    difficulty: 'Hard',
    category: 'Architecture & Athletics',
    meanings: [
      'An arched ceiling or roof',
      'A secure room for storing valuables',
      'To jump over something using hands or a pole',
    ],
    mcqDecoys: ['A type of stone', 'A cooking technique', 'A weather condition'],
  },
  {
    id: 'stalk',
    word: 'Stalk',
    difficulty: 'Hard',
    category: 'Plants & Behaviour',
    meanings: [
      'The stem of a plant',
      'To follow someone in a threatening way',
      'To walk stiffly and proudly',
    ],
    mcqDecoys: ['A type of metal', 'A musical term', 'A legal process'],
    phraseInfo: {
      phrase: 'Stalk and prey',
      origin: 'Hunting terminology',
      meaning: 'To hunt or pursue someone relentlessly',
      originOptions: ['Military terminology', 'Hunting terminology', 'Legal terminology', 'Animal behaviour'],
      meaningOptions: [
        'To walk through fields',
        'To hunt or pursue someone relentlessly',
        'A plant stem',
        'A type of dance',
      ],
    },
  },
  {
    id: 'current',
    word: 'Current',
    difficulty: 'Hard',
    category: 'Physics & Time',
    meanings: [
      'A flow of water, air, or electricity',
      'Happening or existing now',
      'The general course or tendency of events',
    ],
    mcqDecoys: ['A type of plant', 'A cooking technique', 'A musical term'],
    slangInfo: {
      term: 'current',
      meaning: 'Up-to-date or modern',
      era: '1800s',
      eraOptions: ['1700s', '1800s', '1900s', '2000s'],
      meaningOptions: [
        'A flow of electricity',
        'Up-to-date or modern',
        'A water flow',
        'A recent event',
      ],
    },
  },
  {
    id: 'grave',
    word: 'Grave',
    difficulty: 'Hard',
    category: 'Death & Seriousness',
    meanings: [
      'A hole dug in the ground for burial',
      'Serious and concerning',
      'A diacritical mark (`) placed over a letter',
    ],
    mcqDecoys: ['A type of fruit', 'A cooking method', 'A weather tool'],
  },
  {
    id: 'mint',
    word: 'Mint',
    difficulty: 'Hard',
    category: 'Plants & Finance',
    meanings: [
      'A aromatic herb used in cooking',
      'A place where coins are manufactured',
      'In perfect condition',
      'A large amount of money',
    ],
    mcqDecoys: ['A type of metal', 'A weather condition', 'A legal document'],
    phraseInfo: {
      phrase: 'In mint condition',
      origin: 'Coin collecting terminology',
      meaning: 'Perfectly preserved, as new',
      originOptions: ['Botanical terminology', 'Coin collecting terminology', 'Medical terminology', 'Military terminology'],
      meaningOptions: [
        'Flavoured with mint',
        'Perfectly preserved, as new',
        'Freshly made at a mint',
        'Very expensive',
      ],
    },
  },
  {
    id: 'trip',
    word: 'Trip',
    difficulty: 'Hard',
    category: 'Travel & Accidents',
    meanings: [
      'A journey or excursion',
      'To stumble or catch your foot',
      'A hallucinogenic experience from drugs',
    ],
    mcqDecoys: ['A type of plant', 'A musical term', 'A financial product'],
    slangInfo: {
      term: 'trip',
      meaning: 'A drug-induced hallucinatory experience',
      era: '1960s',
      eraOptions: ['1940s', '1950s', '1960s', '1970s'],
      meaningOptions: [
        'A short journey',
        'A drug-induced hallucinatory experience',
        'To fall over',
        'A type of holiday',
      ],
    },
  },
  {
    id: 'ground',
    word: 'Ground',
    difficulty: 'Hard',
    category: 'Surface & Coffee',
    meanings: [
      'The surface of the earth',
      'Past tense of grind',
      'Finely crushed material (as in ground coffee)',
      'To prohibit an aircraft or pilot from flying',
    ],
    mcqDecoys: ['A type of metal', 'A cooking vessel', 'A weather phenomenon'],
  },
  {
    id: 'bound',
    word: 'Bound',
    difficulty: 'Hard',
    category: 'Movement & Obligation',
    meanings: [
      'To leap or jump forward',
      'Tied up or restrained',
      'Travelling towards a destination',
      'Certain or obligated to do something',
    ],
    mcqDecoys: ['A type of fabric', 'A cooking term', 'A musical key'],
    phraseInfo: {
      phrase: 'Bound and determined',
      origin: 'American English',
      meaning: 'Absolutely resolved to do something',
      originOptions: ['British English', 'American English', 'Australian English', 'Canadian English'],
      meaningOptions: [
        'Tied up firmly',
        'Absolutely resolved to do something',
        'Heading in a direction',
        'Certain to happen',
      ],
    },
  },
  {
    id: 'case',
    word: 'Case',
    difficulty: 'Hard',
    category: 'Law & Grammar',
    meanings: [
      'A legal action in court',
      'A container for carrying objects',
      'A grammatical form showing the role of a noun',
      'A specific instance or example',
    ],
    mcqDecoys: ['A type of plant', 'A musical term', 'A weather event'],
    slangInfo: {
      term: 'case',
      meaning: 'To survey a location before committing a crime',
      era: '1900s',
      eraOptions: ['1800s', '1900s', '1950s', '1980s'],
      meaningOptions: [
        'A legal proceeding',
        'To survey a location before committing a crime',
        'A container for items',
        'A grammatical form',
      ],
    },
  },
  {
    id: 'break',
    word: 'Break',
    difficulty: 'Hard',
    category: 'Interruptions & Physics',
    meanings: [
      'To separate into pieces by force',
      'A short rest from activity',
      'A lucky opportunity',
      'A gap or opening in something',
    ],
    mcqDecoys: ['A type of plant', 'A cooking ingredient', 'A weather tool'],
  },
  {
    id: 'cover',
    word: 'Cover',
    difficulty: 'Hard',
    category: 'Music & Protection',
    meanings: [
      'To place something over another to protect it',
      'A recording of a song originally by another artist',
      'To include a topic in a report or lesson',
      'Protection or shelter from danger',
    ],
    mcqDecoys: ['A type of insect', 'A financial term', 'A weather phenomenon'],
    phraseInfo: {
      phrase: 'Cover your tracks',
      origin: 'Hunting terminology',
      meaning: 'To conceal evidence of your actions',
      originOptions: ['Military terminology', 'Hunting terminology', 'Legal terminology', 'Sports terminology'],
      meaningOptions: [
        'To put a cover on something',
        'To conceal evidence of your actions',
        'To record a cover song',
        'To hide from bad weather',
      ],
    },
  },
  {
    id: 'post',
    word: 'Post',
    difficulty: 'Hard',
    category: 'Communication & Structure',
    meanings: [
      'Letters and parcels delivered by mail',
      'A job or official position',
      'An upright pole or pillar',
      'To publish something on social media',
    ],
    mcqDecoys: ['A type of plant', 'A musical term', 'A cooking method'],
    slangInfo: {
      term: 'post',
      meaning: 'To publish something online',
      era: '2000s',
      eraOptions: ['1990s', '2000s', '2010s', '2020s'],
      meaningOptions: [
        'To send mail',
        'To publish something online',
        'A wooden pole',
        'A job position',
      ],
    },
  },
  {
    id: 'note',
    word: 'Note',
    difficulty: 'Hard',
    category: 'Music & Communication',
    meanings: [
      'A single musical sound',
      'A short written message',
      'A piece of paper currency',
      'To pay careful attention to something',
    ],
    mcqDecoys: ['A type of plant', 'A cooking ingredient', 'A weather condition'],
  },
  {
    id: 'sole',
    word: 'Sole',
    difficulty: 'Hard',
    category: 'Shoes & Fish',
    meanings: [
      'The bottom surface of a shoe',
      'The only one; exclusive',
      'A type of flat sea fish',
    ],
    mcqDecoys: ['A type of fabric', 'A musical term', 'A weather event'],
    phraseInfo: {
      phrase: 'Sole proprietor',
      origin: 'Legal terminology',
      meaning: 'The only owner of a business',
      originOptions: ['French law', 'Legal terminology', 'Old English', 'Latin'],
      meaningOptions: [
        'A type of fish',
        'The only owner of a business',
        'The bottom of a shoe',
        'A lonely person',
      ],
    },
  },
  {
    id: 'field',
    word: 'Field',
    difficulty: 'Hard',
    category: 'Agriculture & Science',
    meanings: [
      'An open area of land',
      'A subject of study or work',
      'To receive or deal with questions',
      'A region affected by a force in physics',
    ],
    mcqDecoys: ['A type of insect', 'A cooking technique', 'A musical instrument'],
    slangInfo: {
      term: 'field',
      meaning: 'Working in the real world rather than an office',
      era: '1900s',
      eraOptions: ['1800s', '1900s', '1950s', '1980s'],
      meaningOptions: [
        'An open area of land',
        'Working in the real world rather than an office',
        'A subject of study',
        'A physics concept',
      ],
    },
  },
  {
    id: 'fan',
    word: 'Fan',
    difficulty: 'Hard',
    category: 'Enthusiasm & Cooling',
    meanings: [
      'A device that creates a cooling airflow',
      'An enthusiastic admirer',
      'To spread out in a curved shape',
    ],
    mcqDecoys: ['A type of plant', 'A legal document', 'A cooking vessel'],
  },
  {
    id: 'stem',
    word: 'Stem',
    difficulty: 'Hard',
    category: 'Plants & Origins',
    meanings: [
      'The main stalk of a plant',
      'To stop or restrict the flow of something',
      'To originate from a source',
    ],
    mcqDecoys: ['A type of metal', 'A cooking method', 'A weather phenomenon'],
    phraseInfo: {
      phrase: 'Stem the tide',
      origin: 'Nautical English',
      meaning: 'To stop or slow down an unstoppable process',
      originOptions: ['Military English', 'Nautical English', 'Agricultural English', 'Legal English'],
      meaningOptions: [
        'The stem of a boat',
        'To stop or slow down an unstoppable process',
        'A plant stem',
        'A root system',
      ],
    },
  },
  {
    id: 'catch',
    word: 'Catch',
    difficulty: 'Hard',
    category: 'Sports & Problems',
    meanings: [
      'To grab or seize something in motion',
      'A hidden problem or drawback',
      'A fasten device for a door or window',
      'Something worth obtaining',
    ],
    mcqDecoys: ['A type of plant', 'A weather condition', 'A musical term'],
    slangInfo: {
      term: 'catch',
      meaning: 'A person considered desirable as a partner',
      era: '1800s',
      eraOptions: ['1700s', '1800s', '1900s', '2000s'],
      meaningOptions: [
        'To grab something',
        'A person considered desirable as a partner',
        'A hidden drawback',
        'A door fastening',
      ],
    },
  },
  {
    id: 'index',
    word: 'Index',
    difficulty: 'Hard',
    category: 'Reference & Finance',
    meanings: [
      'An alphabetical list at the back of a book',
      'A financial indicator measuring market performance',
      'The forefinger',
    ],
    mcqDecoys: ['A type of plant', 'A cooking technique', 'A weather event'],
  },
  {
    id: 'fold',
    word: 'Fold',
    difficulty: 'Hard',
    category: 'Textiles & Business',
    meanings: [
      'To bend something over on itself',
      'A group of sheep enclosed together',
      'For a business to fail and close',
    ],
    mcqDecoys: ['A type of metal', 'A cooking vessel', 'A musical instrument'],
    phraseInfo: {
      phrase: 'Return to the fold',
      origin: 'Biblical pastoral imagery',
      meaning: 'To return to a group after being away',
      originOptions: ['Ancient Greek', 'Biblical pastoral imagery', 'Roman military', 'Norse mythology'],
      meaningOptions: [
        'To fold fabric again',
        'To return to a group after being away',
        'A sheep enclosure',
        'To close a business',
      ],
    },
  },
  {
    id: 'plate',
    word: 'Plate',
    difficulty: 'Hard',
    category: 'Geology & Dining',
    meanings: [
      'A flat dish for food',
      'A large section of the Earth\'s crust',
      'Silver or gold covering on a metal object',
      'A full agenda of tasks',
    ],
    mcqDecoys: ['A type of insect', 'A weather tool', 'A musical scale'],
    slangInfo: {
      term: 'plate',
      meaning: 'Have a lot on one\'s plate: to be very busy',
      era: '1900s',
      eraOptions: ['1800s', '1900s', '1950s', '1980s'],
      meaningOptions: [
        'A dish for food',
        'Have a lot on one\'s plate: to be very busy',
        'A tectonic plate',
        'A gold-coated item',
      ],
    },
  },
  {
    id: 'spot',
    word: 'Spot',
    difficulty: 'Hard',
    category: 'Vision & Locations',
    meanings: [
      'A small mark or blemish',
      'To notice or see something',
      'A particular location',
      'A short advertisement on television',
    ],
    mcqDecoys: ['A type of plant', 'A cooking method', 'A legal term'],
  },
  {
    id: 'grip',
    word: 'Grip',
    difficulty: 'Hard',
    category: 'Physical Control & Film',
    meanings: [
      'A firm hold on something',
      'The ability to understand something',
      'A crew member on a film set',
    ],
    mcqDecoys: ['A type of fabric', 'A weather event', 'A musical term'],
    phraseInfo: {
      phrase: 'Get to grips with',
      origin: 'Old English',
      meaning: 'To start to deal with something effectively',
      originOptions: ['Norse', 'Old English', 'French', 'Latin'],
      meaningOptions: [
        'To hold tightly',
        'To start to deal with something effectively',
        'To grab something',
        'To work on a film',
      ],
    },
  },

  // ─── EXPERT (20) ─────────────────────────────────────────────────────────────
  {
    id: 'cleave',
    word: 'Cleave',
    difficulty: 'Expert',
    category: 'Contronym: Split & Cling',
    meanings: [
      'To split apart with a sharp blow',
      'To adhere closely and faithfully',
      'To cut through a substance',
      'To make a path through something',
      'To remain devoted or attached',
    ],
    mcqDecoys: ['A type of plant', 'A cooking measurement', 'A weather tool'],
    phraseInfo: {
      phrase: 'Cleave to your principles',
      origin: 'Old English cleofian',
      meaning: 'To adhere firmly to your beliefs',
      originOptions: ['Middle French', 'Old English cleofian', 'Latin', 'Old Norse'],
      meaningOptions: [
        'To cut something in two',
        'To adhere firmly to your beliefs',
        'To carve meat',
        'To split wood',
      ],
    },
  },
  {
    id: 'sanction',
    word: 'Sanction',
    difficulty: 'Expert',
    category: 'Contronym: Allow & Punish',
    meanings: [
      'Official permission or approval',
      'A penalty imposed for breaking a rule',
      'To officially approve something',
      'To impose penalties on a nation',
      'The threat of punishment to enforce obedience',
    ],
    mcqDecoys: ['A type of plant', 'A musical term', 'A weather system'],
    slangInfo: {
      term: 'sanction',
      meaning: 'Paradoxically means both to permit and to penalise',
      era: '1500s',
      eraOptions: ['1400s', '1500s', '1600s', '1700s'],
      meaningOptions: [
        'Only a punishment',
        'Paradoxically means both to permit and to penalise',
        'Only an approval',
        'A type of law',
      ],
    },
  },
  {
    id: 'fast',
    word: 'Fast',
    difficulty: 'Expert',
    category: 'Contronym: Speed & Stillness',
    meanings: [
      'Moving quickly',
      'Fixed firmly and unable to move',
      'To abstain from eating',
      'Resistant to fading (of dyes)',
      'Acting in a sexually promiscuous way',
    ],
    mcqDecoys: ['A type of plant', 'A cooking vessel', 'A weather term'],
    phraseInfo: {
      phrase: 'Fast and loose',
      origin: 'Carnival gaming',
      meaning: 'To behave in an irresponsible or inconsistent way',
      originOptions: ['Military terminology', 'Carnival gaming', 'Legal terminology', 'Nautical terminology'],
      meaningOptions: [
        'To move very quickly',
        'To behave in an irresponsible or inconsistent way',
        'Both fast and loose',
        'A type of knot',
      ],
    },
  },
  {
    id: 'dust',
    word: 'Dust',
    difficulty: 'Expert',
    category: 'Contronym: Add & Remove',
    meanings: [
      'Fine dry particles of matter',
      'To remove dust from a surface',
      'To sprinkle fine powder onto something',
      'The moment of death (to bite the dust)',
      'Gold dust: something very rare and precious',
    ],
    mcqDecoys: ['A type of plant', 'A musical note', 'A weather tool'],
    slangInfo: {
      term: 'dust',
      meaning: 'To beat someone thoroughly',
      era: '1700s',
      eraOptions: ['1600s', '1700s', '1800s', '1900s'],
      meaningOptions: [
        'Fine dry particles',
        'To beat someone thoroughly',
        'To clean a surface',
        'To sprinkle something',
      ],
    },
  },
  {
    id: 'screen',
    word: 'Screen',
    difficulty: 'Expert',
    category: 'Media & Protection',
    meanings: [
      'A flat surface for displaying images',
      'To test or examine for disease',
      'A partition or barrier',
      'To show a film publicly',
      'To conceal or protect from something',
    ],
    mcqDecoys: ['A type of fabric', 'A cooking method', 'A financial term'],
    phraseInfo: {
      phrase: 'Silver screen',
      origin: 'Early cinema terminology',
      meaning: 'The cinema or film industry',
      originOptions: ['Television terminology', 'Early cinema terminology', 'Theatre terminology', 'Photography terminology'],
      meaningOptions: [
        'A type of silver material',
        'The cinema or film industry',
        'A cinema screen',
        'A protective barrier',
      ],
    },
  },
  {
    id: 'clip',
    word: 'Clip',
    difficulty: 'Expert',
    category: 'Contronym: Attach & Cut',
    meanings: [
      'To fasten something together',
      'To cut or trim with scissors',
      'A short section of film or video',
      'A device that holds objects together',
      'To hit something sharply in passing',
    ],
    mcqDecoys: ['A type of plant', 'A weather event', 'A cooking ingredient'],
    slangInfo: {
      term: 'clip',
      meaning: 'At a fast pace or speed',
      era: '1800s',
      eraOptions: ['1700s', '1800s', '1900s', '2000s'],
      meaningOptions: [
        'To fasten together',
        'At a fast pace or speed',
        'To cut something',
        'A video excerpt',
      ],
    },
  },
  {
    id: 'fine',
    word: 'Fine',
    difficulty: 'Expert',
    category: 'Quality & Penalties',
    meanings: [
      'Of very high quality',
      'A financial penalty',
      'In good health or condition',
      'Consisting of very small particles',
      'Satisfactory or acceptable',
    ],
    mcqDecoys: ['A type of plant', 'A cooking method', 'A weather term'],
  },
  {
    id: 'well',
    word: 'Well',
    difficulty: 'Expert',
    category: 'Health & Structure',
    meanings: [
      'In good health',
      'A deep hole drilled for water or oil',
      'Thoroughly or carefully (done well)',
      'An expression introducing a remark',
      'A sunken enclosed space in a building',
    ],
    mcqDecoys: ['A type of plant', 'A musical term', 'A cooking vessel'],
    phraseInfo: {
      phrase: 'Well and truly',
      origin: 'British English idiom',
      meaning: 'Completely and without question',
      originOptions: ['American English', 'British English idiom', 'Australian English', 'Scottish English'],
      meaningOptions: [
        'In good health',
        'Completely and without question',
        'A source of water',
        'Done with care',
      ],
    },
  },
  {
    id: 'table',
    word: 'Table',
    difficulty: 'Expert',
    category: 'Contronym: Present & Postpone',
    meanings: [
      'A flat surface with legs for placing items',
      'To submit a proposal for discussion (UK)',
      'To postpone a discussion indefinitely (US)',
      'An arrangement of data in rows and columns',
      'A list of multiplication facts',
    ],
    mcqDecoys: ['A type of plant', 'A musical instrument', 'A weather phenomenon'],
    slangInfo: {
      term: 'table',
      meaning: 'Turn the tables: to reverse a situation to one\'s advantage',
      era: '1600s',
      eraOptions: ['1500s', '1600s', '1700s', '1800s'],
      meaningOptions: [
        'A piece of furniture',
        'Turn the tables: to reverse a situation to one\'s advantage',
        'To submit a proposal',
        'To postpone a topic',
      ],
    },
  },
  {
    id: 'set',
    word: 'Set',
    difficulty: 'Expert',
    category: 'Mathematics & Theatre',
    meanings: [
      'A collection of related items',
      'To harden or solidify',
      'The scenery and props for a performance',
      'To arrange or put in a specified position',
      'A series of games forming part of a tennis match',
      'The direction of a current or wind',
    ],
    mcqDecoys: ['A type of plant', 'A cooking method', 'A weather tool'],
    phraseInfo: {
      phrase: 'Set in stone',
      origin: 'Biblical reference',
      meaning: 'Fixed and unable to be changed',
      originOptions: ['Ancient Greek', 'Biblical reference', 'Roman law', 'Celtic tradition'],
      meaningOptions: [
        'Made from stone',
        'Fixed and unable to be changed',
        'To harden like stone',
        'A stone collection',
      ],
    },
  },
  {
    id: 'run',
    word: 'Run',
    difficulty: 'Expert',
    category: 'Movement & Operations',
    meanings: [
      'To move quickly on foot',
      'To manage or operate something',
      'A sequence of identical items',
      'To flow or melt',
      'A point scored in cricket or baseball',
      'A period of continuous performance',
    ],
    mcqDecoys: ['A type of plant', 'A musical note', 'A legal term'],
    slangInfo: {
      term: 'run',
      meaning: 'A smuggling route or illicit journey',
      era: '1800s',
      eraOptions: ['1700s', '1800s', '1900s', '2000s'],
      meaningOptions: [
        'To move on foot',
        'A smuggling route or illicit journey',
        'To manage something',
        'A scored point',
      ],
    },
  },
  {
    id: 'draw',
    word: 'Draw',
    difficulty: 'Expert',
    category: 'Art & Competition',
    meanings: [
      'To make a picture with a pencil or pen',
      'A tied result in a competition',
      'To attract or pull towards',
      'To take out money or a weapon',
      'The act of randomly selecting something',
    ],
    mcqDecoys: ['A type of plant', 'A cooking method', 'A weather event'],
  },
  {
    id: 'check',
    word: 'Check',
    difficulty: 'Expert',
    category: 'Finance & Games',
    meanings: [
      'To verify or examine something',
      'A written order to pay money from a bank',
      'A threat to the king in chess',
      'A pattern of squares',
      'To slow or restrain',
    ],
    mcqDecoys: ['A type of plant', 'A musical term', 'A weather system'],
    phraseInfo: {
      phrase: 'Rain check',
      origin: 'American baseball',
      meaning: 'A request to postpone something to a later time',
      originOptions: ['British cricket', 'American baseball', 'Australian rules', 'Canadian hockey'],
      meaningOptions: [
        'A cheque for rain damage',
        'A request to postpone something to a later time',
        'Checking the weather',
        'A square pattern',
      ],
    },
  },
  {
    id: 'charge',
    word: 'Charge',
    difficulty: 'Expert',
    category: 'Law & Physics',
    meanings: [
      'A formal accusation of a crime',
      'The cost or price of something',
      'To rush forward in an attack',
      'Electrical energy stored in a battery',
      'A responsibility placed on someone',
    ],
    mcqDecoys: ['A type of plant', 'A cooking ingredient', 'A weather tool'],
    slangInfo: {
      term: 'charge',
      meaning: 'In charge: having authority or control',
      era: '1300s',
      eraOptions: ['1200s', '1300s', '1400s', '1500s'],
      meaningOptions: [
        'An accusation',
        'In charge: having authority or control',
        'To rush forward',
        'An electrical property',
      ],
    },
  },
  {
    id: 'part',
    word: 'Part',
    difficulty: 'Expert',
    category: 'Division & Theatre',
    meanings: [
      'A portion or section of a whole',
      'A role played by an actor',
      'To separate or divide',
      'To leave someone\'s company',
      'The line where hair is divided',
    ],
    mcqDecoys: ['A type of plant', 'A cooking method', 'A weather condition'],
  },
  {
    id: 'right',
    word: 'Right',
    difficulty: 'Expert',
    category: 'Direction & Justice',
    meanings: [
      'The opposite direction to left',
      'Morally correct or just',
      'A legal or moral entitlement',
      'To restore to a normal position',
      'Completely or exactly (right in the middle)',
    ],
    mcqDecoys: ['A type of plant', 'A musical term', 'A weather phenomenon'],
    phraseInfo: {
      phrase: 'Right as rain',
      origin: 'British English',
      meaning: 'In perfect health or condition',
      originOptions: ['Australian English', 'British English', 'American English', 'Irish English'],
      meaningOptions: [
        'Moving to the right',
        'In perfect health or condition',
        'Correct about the weather',
        'A legal right',
      ],
    },
  },
  {
    id: 'mean',
    word: 'Mean',
    difficulty: 'Expert',
    category: 'Statistics & Character',
    meanings: [
      'The average value in mathematics',
      'To intend or signify',
      'Unkind or cruel',
      'Of poor quality or low status',
      'Excellent or skilful (informal)',
    ],
    mcqDecoys: ['A type of plant', 'A cooking method', 'A weather tool'],
    slangInfo: {
      term: 'mean',
      meaning: 'Exceptionally skilled or impressive',
      era: '1900s',
      eraOptions: ['1800s', '1900s', '1950s', '1980s'],
      meaningOptions: [
        'Cruel or unkind',
        'Exceptionally skilled or impressive',
        'The mathematical average',
        'Of low quality',
      ],
    },
  },
  {
    id: 'beat',
    word: 'Beat',
    difficulty: 'Expert',
    category: 'Music & Poetry',
    meanings: [
      'The rhythm in music or poetry',
      'To defeat someone in competition',
      'To hit repeatedly',
      'A police officer\'s patrol area',
      'Completely exhausted',
    ],
    mcqDecoys: ['A type of plant', 'A musical instrument', 'A cooking vessel'],
    phraseInfo: {
      phrase: 'Beat around the bush',
      origin: 'Medieval hunting',
      meaning: 'To avoid the main topic',
      originOptions: ['Ancient Roman', 'Medieval hunting', 'Victorian poetry', 'Biblical English'],
      meaningOptions: [
        'To hit a bush',
        'To avoid the main topic',
        'A police patrol',
        'A musical rhythm',
      ],
    },
  },
  {
    id: 'draft',
    word: 'Draft',
    difficulty: 'Expert',
    category: 'Writing & Military',
    meanings: [
      'A preliminary version of a document',
      'Compulsory military service',
      'A current of cold air',
      'To write a preliminary version',
      'Beer drawn from a cask',
    ],
    mcqDecoys: ['A type of plant', 'A cooking technique', 'A weather measurement'],
    slangInfo: {
      term: 'draft',
      meaning: 'Selected for military or sporting service',
      era: '1700s',
      eraOptions: ['1600s', '1700s', '1800s', '1900s'],
      meaningOptions: [
        'A preliminary document',
        'Selected for military or sporting service',
        'A cold air current',
        'A beer from a tap',
      ],
    },
  },
  {
    id: 'buckle',
    word: 'Buckle',
    difficulty: 'Expert',
    category: 'Contronym: Fasten & Collapse',
    meanings: [
      'A clasp for fastening a belt or strap',
      'To fasten with a buckle',
      'To bend or collapse under pressure',
      'To apply oneself with determination',
      'To give way under stress or difficulty',
    ],
    mcqDecoys: ['A type of plant', 'A cooking method', 'A musical term'],
    phraseInfo: {
      phrase: 'Buckle down',
      origin: 'American English',
      meaning: 'To start working hard and seriously',
      originOptions: ['British English', 'American English', 'Australian English', 'Canadian English'],
      meaningOptions: [
        'To fasten a buckle',
        'To start working hard and seriously',
        'To collapse under pressure',
        'To bend metal',
      ],
    },
  },
];

export function getWordById(id: string): WordEntry | undefined {
  return WORD_POOL.find((w) => w.id === id);
}

export function getWordsByDifficulty(difficulty: Difficulty): WordEntry[] {
  return WORD_POOL.filter((w) => w.difficulty === difficulty);
}

export function getDailyWord(): WordEntry {
  const today = new Date();
  const dateString = `${today.getFullYear()}-${today.getMonth()}-${today.getDate()}`;
  let hash = 0;
  for (let i = 0; i < dateString.length; i++) {
    hash = ((hash << 5) - hash + dateString.charCodeAt(i)) | 0;
  }
  const index = Math.abs(hash) % WORD_POOL.length;
  return WORD_POOL[index];
}

export function shuffleArray<T>(array: T[]): T[] {
  const arr = [...array];
  for (let i = arr.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [arr[i], arr[j]] = [arr[j], arr[i]];
  }
  return arr;
}

export function getShuffledWords(): WordEntry[] {
  return shuffleArray(WORD_POOL);
}
